### ISSUE TITLE
[FEAT]: Implement Dark and Light Modes for the webpage

### ISSUE THREAD

**Issue by Anushka-Pote** [nitendra2211/SignIn-Page#13]
Implement Dark and Light Modes for the webpage to match the aesthetics and provide an option to the users for better experience

**Comment by nitendra2211** [comment]
ok you can go for it.

**Comment by Anushka-Pote** [comment]
On it. 
Do assign labels to this and coming PR for hacktoberfest and gssoc-ext, Thanks
