### ISSUE TITLE
Device Detection and Auto Sign-In Suggestion

### ISSUE THREAD

**Issue by Anushka-Pote** [nitendra2211/SignIn-Page#18]
Implement device detection using localStorage to remember users who have previously signed in. Provide an option to suggest auto sign-in by pre-filling the email field and displaying a message to enhance the user experience on returning to the sign-in page. Add a "Remember Me" checkbox to store user credentials for future sessions.

**Comment by nitendra2211** [comment]
okay you can add it. I assigned it to you.
