### ISSUE TITLE
login box is improperly placed

### ISSUE THREAD

**Issue by abhayksahu369** [nitendra2211/SignIn-Page#2]
![Screenshot 2024-10-09 110113](https://github.com/user-attachments/assets/e7609be6-0963-40c4-8746-4299b68c5ae0)

add hacktober ,gssoc-ext and level tag here and assign this task to me ,let me fix it

**Comment by biswajit-sarkar-007** [comment]
Hi @nitendra2211,

I see that this issue is open and would love to work on it. Could you please assign it to me?

Thank you!
