### ISSUE TITLE
Add CODE_OF_CONDUCT.md file

### ISSUE THREAD

**Issue by Maryam0330** [nitendra2211/SignIn-Page#9]
I would like to add a `CODE_OF_CONDUCT.md` file to the repository to establish clear guidelines for acceptable behavior in the project. This will help foster an inclusive and positive environment for contributors, ensuring a respectful and collaborative atmosphere.

**Comment by Maryam0330** [comment]
@nitendra2211 Please assign me this task under the `gssoc-ext` , `level3` labels.

**Comment by nitendra2211** [comment]
okay I have assigned it to you.

**Comment by Maryam0330** [comment]
@nitendra2211 Hey, please add the `gssoc-ext` label.
